#!/usr/bin/env python3
"""
Audit TMD seed set: compare embedded terms to approved list, term frequencies,
and sample papers for false-positive review.

Read-only DB. Writes only under data/tmd_field_discovery/audit/.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import re
import sqlite3
import sys
from collections import Counter
from pathlib import Path

# Terms to spot-check for generic / high false-positive risk (physics-dependent).
SUSPICIOUS_TRIGGER_TERMS: tuple[str, ...] = (
    "generalized parton distribution",
    "light cone gauge",
    "light-cone gauge",
    "wilson line",
    "transversity",
    "azimuthal asymmetry",
    "transverse momentum distribution",
)


def parse_terms_from_build_script(build_script: Path) -> list[str]:
    text = build_script.read_text(encoding="utf-8")
    m = re.search(r"_TMD_LINES\s*=\s*\"\"\"(.*?)\"\"\"", text, re.DOTALL)
    if not m:
        raise ValueError(f"Could not find _TMD_LINES block in {build_script}")
    return [
        ln.strip()
        for ln in m.group(1).strip().splitlines()
        if ln.strip()
    ]


def load_approved_terms(path: Path) -> list[str]:
    raw = path.read_text(encoding="utf-8")
    out: list[str] = []
    for ln in raw.splitlines():
        s = ln.strip()
        if s and not s.startswith("#"):
            out.append(s)
    return out


def duplicate_entries(terms: list[str]) -> list[str]:
    c = Counter(terms)
    return sorted([t for t, n in c.items() if n > 1])


def audit_term_lists(
    terms_script: list[str],
    terms_approved: list[str],
) -> dict:
    set_s = set(terms_script)
    set_a = set(terms_approved)
    missing = sorted(set_a - set_s)
    extra = sorted(set_s - set_a)
    dup_script = duplicate_entries(terms_script)
    dup_approved = duplicate_entries(terms_approved)
    exact_sequence = terms_script == terms_approved
    exact_as_set = set_s == set_a and len(terms_script) == len(terms_approved)
    return {
        "num_terms_in_script": len(terms_script),
        "num_terms_approved": len(terms_approved),
        "missing_terms": missing,
        "extra_terms": extra,
        "duplicate_terms_in_script": dup_script,
        "duplicate_terms_in_approved_file": dup_approved,
        "exact_match_sequence": exact_sequence,
        "exact_match_as_sets_same_sizes": exact_as_set,
        "exact_match": exact_sequence,
    }


def load_seed_rows(seed_csv: Path) -> list[tuple[int, list[str]]]:
    rows: list[tuple[int, list[str]]] = []
    with open(seed_csv, newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        if not r.fieldnames or "recid" not in r.fieldnames:
            raise ValueError(f"seed_set.csv missing recid column: {seed_csv}")
        has_mt = "matched_terms" in r.fieldnames
        for row in r:
            rid = int(row["recid"])
            if has_mt and row.get("matched_terms"):
                terms = [t for t in row["matched_terms"].split("|") if t.strip()]
            else:
                terms = []
            rows.append((rid, terms))
    return rows


def term_frequencies_from_seed(seed_rows: list[tuple[int, list[str]]]) -> list[tuple[str, int]]:
    ctr: Counter[str] = Counter()
    for _, terms in seed_rows:
        for t in terms:
            ctr[t] += 1
    return sorted(ctr.items(), key=lambda x: (-x[1], x[0]))


def fetch_papers(
    conn: sqlite3.Connection,
    recids: list[int],
) -> dict[int, tuple[str, str]]:
    if not recids:
        return {}
    out: dict[int, tuple[str, str]] = {}
    chunk = 400
    for i in range(0, len(recids), chunk):
        part = recids[i : i + chunk]
        qmarks = ",".join("?" * len(part))
        cur = conn.execute(
            f"""
            SELECT control_number, IFNULL(title, ''), IFNULL(abstract, '')
            FROM papers
            WHERE control_number IN ({qmarks})
            """,
            part,
        )
        for cn, title, abstract in cur.fetchall():
            out[int(cn)] = (title or "", abstract or "")
    return out


def write_report_md(
    path: Path,
    term_audit: dict,
    top_terms: list[tuple[str, int]],
    suspicious_in_top: list[str],
    db_used: str,
) -> None:
    exact = term_audit.get("exact_match")
    lines = [
        "# TMD seed set audit",
        "",
        "This report is generated by `scripts/audit_tmd_seed_set.py`.",
        "",
        "## 1. Term list vs approved file",
        "",
        f"- **Approved reference:** `data/tmd_field_discovery/audit/approved_tmd_terms.txt`",
        f"- **Terms in build script (`_TMD_LINES`):** {term_audit['num_terms_in_script']}",
        f"- **Terms in approved file:** {term_audit['num_terms_approved']}",
        f"- **Exact sequence match:** {'yes' if exact else 'no'}",
        f"- **Missing vs script (in approved, not in script):** {len(term_audit['missing_terms'])}",
        f"- **Extra vs approved (in script, not in approved):** {len(term_audit['extra_terms'])}",
        "",
        "## 2. Top contributing terms (from seed_set.csv)",
        "",
        "| Rank | Term | Seed papers |",
        "|------|------|-------------|",
    ]
    for i, (t, n) in enumerate(top_terms[:15], 1):
        esc = t.replace("|", "\\|")
        lines.append(f"| {i} | {esc} | {n} |")
    lines.extend(
        [
            "",
            "## 3. Suspicious / broad triggers",
            "",
            "These phrases often appear outside strict TMD physics; presence in the seed set",
            "does not prove relevance—manual review of samples below is required.",
            "",
        ]
    )
    for st in suspicious_in_top:
        lines.append(f"- **{st}** (also in top frequency list)")
    if not suspicious_in_top:
        lines.append("- *(None of the pre-flagged suspicious terms appeared in top-N frequency export.)*")
    lines.extend(
        [
            "",
            "## 4. Spot-check interpretation",
            "",
            "- Review `sample_seed_papers.csv` (random 50) and `sample_suspicious_terms.csv`",
            "  (up to 10 papers per flagged trigger term).",
            f"- **DB used for titles/abstracts:** read-only `{db_used}`",
            "",
            "## 5. Recommendation",
            "",
        ]
    )
    if exact and not term_audit.get("duplicate_terms_in_script"):
        lines.append(
            "- **Term list integrity:** Embedded list matches `approved_tmd_terms.txt`."
        )
        lines.append(
            "- **Seed usability:** Acceptable as a **high-recall** screen if reviewers tolerate "
            "noise from broad phrases (e.g. Drell–Yan normalization, gauge/Wilson-line jargon in non-TMD papers)."
        )
        lines.append("- **Action:** Proceed to next stage **or** tighten/remove specific terms after manual sample review—**do not** auto-delete terms based on this script alone.")
    else:
        lines.append("- **Term list integrity:** Mismatch or duplicates detected—**reconcile** `build_tmd_seed_set.py` and `audit/approved_tmd_terms.txt`, then rerun `build_tmd_seed_set.py` if the embedded list changes.")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Audit TMD seed set and term lists")
    ap.add_argument(
        "--build-script",
        type=Path,
        default=Path("scripts/build_tmd_seed_set.py"),
    )
    ap.add_argument(
        "--approved-terms",
        type=Path,
        default=Path("data/tmd_field_discovery/audit/approved_tmd_terms.txt"),
    )
    ap.add_argument(
        "--seed-csv",
        type=Path,
        default=Path("data/tmd_field_discovery/seed_set.csv"),
    )
    ap.add_argument(
        "--db",
        default="inspire_mirror.sqlite",
        help="SQLite DB (read-only); use inspire.sqlite if mirror missing",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=Path("data/tmd_field_discovery/audit"),
    )
    ap.add_argument("--random-seed", type=int, default=42)
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    build_script = (repo_root / args.build_script).resolve()
    approved_path = (repo_root / args.approved_terms).resolve()
    seed_csv = (repo_root / args.seed_csv).resolve()
    out_dir = (repo_root / args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    db_path = (repo_root / args.db).resolve()
    if not db_path.is_file():
        alt = repo_root / "inspire.sqlite"
        if alt.is_file():
            print(
                f"Note: using {alt.name} (read-only); {args.db} not found.",
                file=sys.stderr,
            )
            db_path = alt.resolve()
        else:
            print(f"Error: database not found: {db_path}", file=sys.stderr)
            return 1

    if not build_script.is_file():
        print(f"Error: {build_script}", file=sys.stderr)
        return 1
    if not approved_path.is_file():
        print(f"Error: approved terms file missing: {approved_path}", file=sys.stderr)
        return 1
    if not seed_csv.is_file():
        print(f"Error: seed_set.csv missing: {seed_csv}", file=sys.stderr)
        return 1

    terms_script = parse_terms_from_build_script(build_script)
    terms_approved = load_approved_terms(approved_path)
    term_audit = audit_term_lists(terms_script, terms_approved)

    term_list_path = out_dir / "term_list_audit.json"
    with open(term_list_path, "w", encoding="utf-8") as f:
        json.dump(term_audit, f, indent=2)
        f.write("\n")

    seed_rows = load_seed_rows(seed_csv)
    seed_recids = [r[0] for r in seed_rows]
    freq = term_frequencies_from_seed(seed_rows)
    freq_path = out_dir / "matched_term_frequencies.csv"
    with open(freq_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["term", "num_seed_papers"])
        for t, n in freq:
            w.writerow([t, n])

    rng = random.Random(args.random_seed)
    conn_uri = db_path.expanduser().resolve().as_uri() + "?mode=ro"
    conn = sqlite3.connect(conn_uri, uri=True)

    # Random sample of 50 seed papers
    sample_n = min(50, len(seed_recids))
    random_pick = rng.sample(seed_recids, sample_n) if seed_recids else []
    meta = fetch_papers(conn, random_pick)
    sample_seed_path = out_dir / "sample_seed_papers.csv"
    rid_to_terms = {r: t for r, t in seed_rows}
    with open(sample_seed_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["recid", "matched_terms", "title", "abstract", "sample_kind"])
        for rid in sorted(random_pick):
            title, abstract = meta.get(rid, ("", ""))
            w.writerow(
                [
                    rid,
                    "|".join(rid_to_terms.get(rid, [])),
                    title,
                    abstract,
                    "random_n50",
                ]
            )

    # Suspicious-term samples: up to 10 papers per trigger
    suspicious_path = out_dir / "sample_suspicious_terms.csv"
    with open(suspicious_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(
            ["trigger_term", "recid", "matched_terms", "title", "abstract"]
        )
        for trig in SUSPICIOUS_TRIGGER_TERMS:
            pool = [
                rid
                for rid, terms in seed_rows
                if trig in terms
            ]
            k = min(10, len(pool))
            pick = rng.sample(pool, k) if pool else []
            meta_s = fetch_papers(conn, pick)
            for rid in pick:
                title, abstract = meta_s.get(rid, ("", ""))
                w.writerow(
                    [
                        trig,
                        rid,
                        "|".join(rid_to_terms.get(rid, [])),
                        title,
                        abstract,
                    ]
                )

    conn.close()

    top_terms = freq[:25]
    suspicious_in_top = [
        x for x in SUSPICIOUS_TRIGGER_TERMS if x in {t for t, _ in freq[:30]}
    ]

    report_path = out_dir / "audit_report.md"
    write_report_md(
        report_path,
        term_audit,
        freq,
        suspicious_in_top,
        str(db_path),
    )

    print(f"Wrote {term_list_path}")
    print(f"Wrote {freq_path}")
    print(f"Wrote {sample_seed_path}")
    print(f"Wrote {suspicious_path}")
    print(f"Wrote {report_path}")
    print()
    print("term list exact_match:", term_audit["exact_match"])
    if term_audit["missing_terms"][:3]:
        print("missing (sample):", term_audit["missing_terms"][:5])
    if term_audit["extra_terms"][:3]:
        print("extra (sample):", term_audit["extra_terms"][:5])
    print("top 5 terms by frequency:")
    for t, n in freq[:5]:
        print(f"  {t!r}: {n}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
